### ISSUE TITLE
[Feature Request] Compability with Styled Player List

### ISSUE THREAD

**Issue by elhertz** [beabfc/afkdisplay#1]
It'd be nice to have a placeholder so I can make it work with [Styled Player List](https://modrinth.com/mod/styledplayerlist)

Something like afkdisplay.prefix
Is it possible?

**Comment by beabfc** [comment]
I will have a look at it. Thank you for the suggestion.

**Comment by beabfc** [comment]
I think the best way to do it is to add the placeholder `afkisplay:prefix`which will be an empty string if the player isn't afk and the configured afk prefix if the player is afk.

**Comment by beabfc** [comment]
Okay this is actually way more difficult than I thought because we change the return value of `getPlayerListName`. Closing as wontfix for now, but I will gladly accept any PRs.

**Comment by beabfc** [comment]
I added the placeholder `player:afk` in the latest version.
