### ISSUE TITLE
Can be marked as 1.20.1 compatible

### ISSUE THREAD

**Issue by sternschnaube** [beabfc/afkdisplay#10]

**Comment by elamperti** [comment]
Is this a question or a statement?

**Comment by sternschnaube** [comment]
A statement, since no '?' 😅

**Comment by TeRacksito** [comment]
In my case it doesn't allow me to load, it say incompatible version. How did you do to be able to load on 1.20.1?

**Comment by sternschnaube** [comment]
I still use version 1.0.2, downgrade and it should work for you.
