### ISSUE TITLE
1.20.1 Update?

### ISSUE THREAD

**Issue by xMathayus** [beabfc/afkdisplay#12]
any chance to get this updated to 1.20.1

**Comment by ReedGraf** [comment]
The code is updated by the looks of things but, it just hasn't been compiled and released. @beabfc any comment?

**Comment by sakura-ryoko** [comment]
This issue is outdated since 1.20.2 btw.

**Comment by beabfc** [comment]
Please use @sakura-ryoko updated fork [sakura-ryoko/afkplus](https://github.com/sakura-ryoko/afkplus) instead.
