### ISSUE TITLE
Mod does not load on integrated servers

### ISSUE THREAD

**Issue by haykam821** [beabfc/afkdisplay#4]
This mod specifies its environment as `server`, which applies to dedicated servers only, while the mod could work on integrated servers in theory.

**Comment by sakura-ryoko** [comment]
I got this working in my fork also.

**Comment by beabfc** [comment]
Please use @sakura-ryoko updated fork [sakura-ryoko/afkplus](https://github.com/sakura-ryoko/afkplus) instead.
