### ISSUE TITLE
[Request] /afk command

### ISSUE THREAD

**Issue by toydotgame** [beabfc/afkdisplay#5]
Hi, I'm moving from Spigot/Paper to Fabric, and so I've been replacing most of my plugins with datapacks and Fabric mods. My current task is finding the best replacement for the plugin ["AFK"](https://dev.bukkit.org/projects/afk/), which I have been using for years now. I've set up my config with AfkDisplay to be as close to the behaviour as the plugin I used to use, but with two main differences:
* Players going AFK and returning from AFK print a message into chat, and
* Players can run `/afk` or `/afk <reason>` to go AFK on-demand instead of waiting 10 minutes. `/afk <reason>` will also print the reason in the AFK chat message to the server.

Quite a few of my players use the functionality of the `/afk` command, and I'd really like to see similar functionality in this mod. Just a manual way to grey out your name at a minimum would be nice.

I had a look around the code a bit and line 27 of /mixin/ServerPlayNetworkMixin.java looks to be around about the area which triggers everything after x amount of time. I'm a Spigot dev and not a Fabric one though, so that's why this isn't a pull request as I don't know how to handle player commands. :)
https://github.com/beabfc/afkdisplay/blob/2c76f5e85b48d53fccf7af3c598da73b1b1fc274/src/main/java/io/github/beabfc/afkdisplay/mixin/ServerPlayNetworkMixin.java#L27

**Comment by beabfc** [comment]
I don't have the time to implement this at the moment but will happily review any pull request.

**Comment by beabfc** [comment]
Done (v1.1.0).
