### ISSUE TITLE
config for mod is different

### ISSUE THREAD

**Issue by AspectV0id** [beabfc/afkdisplay#9]
Hi I just installed the mod and the config completely different in the file only is:
timeoutSeconds = 180
resetOnMovement = false
resetOnLook = false
afkColor = "gray"
afkPrefix = "[AFK] "

do u know why and how to fix it?
a /afk command would be very cool too
have a nice day :)

**Comment by beabfc** [comment]
You are using an old version which used another configuration schema. The /afk command and new config were first implemented in v1.1.0.
